(function(g){var window=this;var R4=function(a,b,c){var d=b.va();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.jc(c?c:"mqdefault.jpg");var f=b instanceof g.hC&&b.lengthSeconds?g.DM(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.ZD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.hC?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.lj||g.oN("Tonton $TITLE",{TITLE:b.title}),duration:f,url:b.gi(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.aE&&(d.playlist_length=b.getLength());a.update(d)},S4=function(a,b){g.W.call(this,{F:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},T4=function(a){g.W.call(this,{F:"div",
X:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},L:[{F:"div",I:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{F:"span",I:"ytp-upnext-top",L:[{F:"span",I:"ytp-upnext-header",W:"Berikutnya"},{F:"span",I:"ytp-upnext-title",W:"{{title}}"},{F:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{F:"a",I:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Putar video selanjutnya"},L:[{F:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
L:[{F:"circle",I:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",I:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",I:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",I:"ytp-upnext-bottom",L:[{F:"span",I:"ytp-upnext-cancel"},{F:"span",I:"ytp-upnext-paused",
W:"Putar otomatis dijeda"}]}]});this.C=null;var b=this.u["ytp-upnext-cancel"];this.C=new g.W({F:"button",X:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Batalkan pemutaran otomatis"},W:"Batalkan"});g.H(this,this.C);this.C.ga("click",this.BI,this);this.C.o(b);this.w=a;this.K=this.u["ytp-svg-autoplay-ring"];this.G=this.D=this.A=this.B=null;this.H=new g.J(this.Ml,5E3,this);g.H(this,this.H);this.J=0;this.M(this.u["ytp-upnext-autoplay-icon"],"click",this.oK);this.vy();this.M(a,
"autonavvisibility",this.vy);this.M(a,"mdxnowautoplaying",this.GJ);this.M(a,"mdxautoplaycanceled",this.HJ);this.M(a,"mdxautoplayupnext",this.NA);3==this.w.getPresentingPlayerType()&&(a=(a=g.PK(g.IK(this.w)))?a.fD():null)&&this.NA(a)},U4=function(a,b){if(!a.A){g.Go("a11y-announce","Berikutnya "+a.B.title);
a.J=(0,g.Kq)();a.A=new g.J((0,g.x)(a.To,a,b),25);a.To(b);var c=b||g.S(a.w.O().experiments,"autoplay_time")||1E4;a.w.la("onAutonavCoundownStarted",c)}g.jn(a.element,"ytp-upnext-autoplay-paused")},W4=function(a){V4(a);
a.J=(0,g.Kq)();a.To();g.K(a.element,"ytp-upnext-autoplay-paused")},V4=function(a){a.A&&(a.A.dispose(),a.A=null)},X4=function(a,b){b=void 0===b?!1:b;
if(g.R(a.w.O().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.B.va(),a.Ml(),a.D=new Notification("Berikutnya",{body:c.title,icon:c.jc()}),a.G=a.M(a.D,"click",a.fK),a.H.start())}V4(a);a.w.nextVideo(!1,b)},Y4=function(a){S4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.w=new g.W({F:"div",I:"ytp-subscribe-card",L:[{F:"img",I:"ytp-author-image",N:{src:b.Od}},{F:"div",I:"ytp-subscribe-card-right",L:[{F:"div",I:"ytp-author-name",W:b.author},{F:"div",I:"html5-subscribe-button-container"}]}]});g.H(this,this.w);this.w.o(this.element);this.A=new g.FR("Subscribe",null,"Unsubscribe",null,!0,!1,b.Qf,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.A);this.A.o(this.w.u["html5-subscribe-button-container"]);this.hide()},Z4=function(a){var b=
a.O(),c=g.Ks||g.dg?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.W.call(this,{F:"a",X:e,N:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{F:"div",I:"ytp-videowall-still-image",N:{style:"{{background}}"}},{F:"span",I:"ytp-videowall-still-info",L:[{F:"span",I:"ytp-videowall-still-info-bg",L:[{F:"span",I:"ytp-videowall-still-info-content",N:c,L:[{F:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{F:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{F:"span",I:"ytp-videowall-still-info-live",W:"Live"},{F:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{F:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{F:"span",W:"{{playlist_length}}"},")"]}]},{F:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Video Mix",{F:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.C=d;this.w=a;this.A=null;this.B=new g.Q(this);g.H(this,this.B);this.ga("click",this.G);this.ga("keypress",this.H);this.B.M(a,"videodatachange",this.D);g.iL(a,this.element,this);this.D()},$4=function(a){g.kL(a.w,a.element);
var b=a.A.va().videoId,c=a.A.getPlaylistId();g.dU(a.w.app,b,a.A.Fb,c,void 0,void 0)},a5=function(a){S4.call(this,a,"videowall-endscreen");
this.G=a;this.D=0;this.A=[];this.H=this.S=this.C=null;this.J=this.V=!1;this.T=null;this.B=new g.Q(this);g.H(this,this.B);this.K=new g.J(g.Na(g.K,this.element,"ytp-show-tiles"),0);g.H(this,this.K);var b=new g.W({F:"button",X:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Sebelumnya"},L:[g.LM()]});g.H(this,b);b.o(this.element);b.ga("click",this.MF,this);this.P=new g.Fu({F:"div",I:"ytp-endscreen-content"});g.H(this,this.P);this.P.o(this.element);b=new g.W({F:"button",X:["ytp-button","ytp-endscreen-next"],
N:{"aria-label":"Berikutnya"},L:[g.MM()]});g.H(this,b);b.o(this.element);b.ga("click",this.LF,this);this.w=new T4(a);g.H(this,this.w);g.fL(this.player,this.w.element,4);this.hide()},b5=function(a){return g.gL(a.player)&&a.pu()&&!a.H},c5=function(a,b){return(0,g.ee)(b.suggestions,function(c){c=g.pN(a.G.O(),c);
g.H(a,c);return c})},d5=function(a){var b=a.Vq();
b!=a.V&&(a.V=b,a.player.R("autonavvisibility"))},f5=function(a){g.tQ.call(this,a);
this.o=null;this.u=new g.Q(this);g.H(this,this.u);this.w=a.O();e5(a)?this.o=new a5(this.player):this.w.Ka?this.o=new Y4(this.player):this.o=new S4(this.player);g.H(this,this.o);g.fL(this.player,this.o.element,4);this.Qz();this.u.M(a,"videodatachange",this.Qz,this);this.u.M(a,g.YD("endscreen"),this.SE,this);this.u.M(a,"crx_endscreen",this.TE,this)},e5=function(a){a=a.O();
return a.na&&!a.Ka};
g.r(S4,g.W);S4.prototype.create=function(){this.created=!0};
S4.prototype.destroy=function(){this.created=!1};
S4.prototype.pu=function(){return!1};
S4.prototype.Vq=function(){return!1};g.r(T4,g.W);g.h=T4.prototype;g.h.Ml=function(){this.D&&(this.H.stop(),this.Ta(this.G),this.G=null,this.D.close(),this.D=null)};
g.h.vy=function(){g.Ku(this,g.JK(this.w))};
g.h.fK=function(){window.focus();this.Ml()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.To=function(a){a=a||g.S(this.w.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.Kq)()-this.J,a);a=Math.min(b/a,1);this.K.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.w.getPresentingPlayerType()?X4(this,!0):this.A&&this.A.start()};
g.h.oK=function(a){!g.Wd(this.C.element,g.$q(a))&&g.wN(a,this.w)&&X4(this)};
g.h.BI=function(){g.LK(this.w,!0)};
g.h.GJ=function(a){this.w.getPresentingPlayerType();this.show();U4(this,a)};
g.h.NA=function(a){this.w.getPresentingPlayerType();this.B&&this.B.va().videoId==a.va().videoId||(this.B=a,R4(this,a,"hqdefault.jpg"))};
g.h.HJ=function(){this.w.getPresentingPlayerType();V4(this);this.hide()};
g.h.Y=function(){V4(this);this.Ml();g.W.prototype.Y.call(this)};g.r(Y4,S4);g.r(Z4,g.W);Z4.prototype.G=function(a){g.wN(a,this.w,this.C,this.A.Fb||void 0)&&$4(this)};
Z4.prototype.H=function(a){switch(a.keyCode){case 13:case 32:g.er(a)||($4(this),g.dr(a))}};
Z4.prototype.D=function(){var a=this.w.getVideoData(),b=this.w.O();this.C=a.ac?!1:b.u};g.r(a5,S4);g.h=a5.prototype;g.h.create=function(){S4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.C=c5(this,a),this.S=a);this.Of();this.B.M(this.player,"appresize",this.Of);this.B.M(this.player,"onVideoAreaChange",this.Of);this.B.M(this.player,"videodatachange",this.NF);this.B.M(this.player,"autonavchange",this.Wq);this.B.M(this.player,"autonavcancel",this.KF);a=this.S.autonavState;a!=this.T&&this.Wq(a);this.B.M(this.element,"transitionend",this.FL)};
g.h.destroy=function(){g.Ss(this.B);g.zi(this.A);this.A=[];this.C=null;S4.prototype.destroy.call(this);g.jn(this.element,"ytp-show-tiles");this.K.stop();this.T=this.S.autonavState};
g.h.pu=function(){return 1!=this.S.autonavState};
g.h.show=function(){S4.prototype.show.call(this);g.jn(this.element,"ytp-show-tiles");this.player.O().o?g.Zm(this.K):this.K.start();(this.J||this.H&&this.H!=this.S.clientPlaybackNonce)&&g.LK(this.player,!1);b5(this)?(d5(this),2==this.S.autonavState?g.R(this.player.O().experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?X4(this.w,!0):U4(this.w):3==this.S.autonavState&&W4(this.w)):(g.LK(this.player,!0),d5(this))};
g.h.hide=function(){S4.prototype.hide.call(this);W4(this.w);d5(this)};
g.h.FL=function(a){g.$q(a)==this.element&&this.Of()};
g.h.Of=function(){if(this.C&&this.C.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.XK(this.G,!0,this.G.isFullscreen()),b=g.nD(this.G);b&&(b=b.Rb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(u)n-=t*m,b+=2;else if(y)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.ld(a.width/m||1,1,1.21);n*=g.ld(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.P.element;g.sg(a,m,n);g.ag(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.w;f=this.C[0];c.B=f;R4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",b5(this));d5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.md(q+this.D,l),0!=t){u=this.A[c];u||(u=new Z4(this.player),this.A[c]=u,a.appendChild(u.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),C=Math.floor(n*(k+t)/e)-y-4,G=Math.floor(m*(f+t)/b)-B-4;g.ig(u.element,B,y);g.sg(u.element,G,C);g.ag(u.element,"transitionDelay",(k+f)/20+"s");g.L(u.element,"ytp-videowall-still-mini",1==t);g.L(u.element,"ytp-videowall-still-large",2<t);t=u;q=this.C[q];t.A!=q&&(t.A=q,R4(t,q,g.gn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),(q=(q=q.Fb)&&q.itct)&&g.jL(t.w,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.A.length-1;b>=c;b--)e=this.A[b],g.Sd(e.element),g.yi(e);this.A.length=c}};
g.h.NF=function(){var a=this.player.getVideoData();this.S!=a&&(this.D=0,this.C=c5(this,a),this.S=a,this.Of())};
g.h.LF=function(){this.D+=this.A.length;this.Of()};
g.h.MF=function(){this.D-=this.A.length;this.Of()};
g.h.kE=function(){return!!this.w.A};
g.h.Wq=function(a){1==a?(this.J=!1,this.H=this.S.clientPlaybackNonce,V4(this.w),this.Ga()&&this.Of()):(this.J=!0,this.Ga()&&b5(this)&&(2==a?U4(this.w):3==a&&W4(this.w)))};
g.h.KF=function(a){if(a){for(a=0;a<this.A.length;a++)g.lL(this.G,this.A[a].element,!0);this.Wq(1)}else this.H=null,this.J=!1;this.Of()};
g.h.Vq=function(){return this.Ga()&&b5(this)};g.r(f5,g.tQ);g.h=f5.prototype;g.h.Yw=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!e5(this.player)||b;a=a.Oh||g.hz(a.Ma);var c=g.yT(this.player.app);return b&&!a&&!c};
g.h.Xw=function(){return this.o.Vq()};
g.h.cE=function(){return this.Xw()?this.o.kE():!1};
g.h.Y=function(){g.zR(this.player.app,"endscreen",void 0);g.tQ.prototype.Y.call(this)};
g.h.load=function(){g.tQ.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.tQ.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.SE=function(a){this.Yw()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.TE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Qz=function(){g.zR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.VD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.H(this,a);var b=new g.VD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.H(this,b);g.bL(this.player,[a,b])};g.JQ.endscreen=f5;})(_yt_player);
