(function(g){var window=this;var SCa=function(a,b){return g.Wb(a,b)},i6=function(a){g.Rm(a,"zx",g.xb());
return a},j6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Um(a.o,b,c)},TCa=function(a,b){var c=[];
g.Fk(b,function(a){try{var b=g.qD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.pD(b)&&c.push(a):c.push(a)},a);
return c},UCa=function(a,b){var c=TCa(a,b);
(0,g.D)(c,function(a){g.qD.prototype.remove.call(this,a)},a)},VCa=function(a){if(a.Id){if(a.Id.locationOverrideToken)return{locationOverrideToken:a.Id.locationOverrideToken};
if(null!=a.Id.latitudeE7&&null!=a.Id.longitudeE7)return{latitudeE7:a.Id.latitudeE7,longitudeE7:a.Id.longitudeE7}}return null},WCa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&g.Mm(e,d);return e},XCa=function(a){g.fG[a]&&(a=g.fG[a],(0,g.D)(a,function(a){g.dG[a]&&delete g.dG[a]}),a.length=0)},YCa=function(a){var b=g.cG();
if(b)if(b.clear(a),a)XCa(a);else for(var c in g.fG)XCa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Cm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",ZCa(this,a.capabilities||""),$Ca(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},ZCa=function(a,b){a.capabilities.clear();
(0,g.Ud)(b.split(","),g.Fa(SCa,aDa)).forEach(function(b){a.capabilities.add(b)})},$Ca=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},bDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},cDa=function(a){return new l6(a)},dDa=function(a){return g.za(a)?(0,g.I)(a,cDa):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.za(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},eDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.Ka(a,function(a){return m6(a,b)})},fDa=function(){var a=(0,g.dH)();
a&&UCa(a,a.o.de(!0))},s6=function(){var a=g.gH("yt-remote-connected-devices")||[];
g.fb(a);return a},gDa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},hDa=function(a){g.fH("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.gH("yt-remote-device-id");a||(a=p6(),g.fH("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Oa(a,b);g.iH()&&g.ib(a,b);a=gDa(a);if(g.Pa(a))try{g.OG("remote_sid")}catch(c){}else try{g.NG("remote_sid",a.join(","),-1)}catch(c){}},iDa=function(){return g.gH("yt-remote-session-browser-channel")},jDa=function(){return g.gH("yt-remote-local-screens")||[]},kDa=function(){g.fH("yt-remote-lounge-token-expiration",!0,86400)},lDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(jDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.qm)(c,function(a){return!g.Oa(b,a)})&&kDa();
g.fH("yt-remote-local-screens",a,31536E3)},mDa=function(a,b){g.fH("yt-remote-session-browser-channel",a);
g.fH("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Oa(c,d)||c.push(d);hDa(c);v6()},w6=function(a){a||(g.hH("yt-remote-session-screen-id"),g.hH("yt-remote-session-video-id"));
v6();a=s6();g.Ta(a,u6());hDa(a)},nDa=function(){if(!x6){var a=g.BD();
a&&(x6=new g.kD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},oDa=function(){var a=window.document.createElement("a");
g.id(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Bb(a)},pDa=function(a,b){var c=g.Nd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.jd(c,g.le("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},qDa=function(){var a=oDa(),b=window.document.getElementById(a),c=b&&g.nF(b,"loaded");
c||b&&!c||(b=pDa(a,function(){g.nF(b,"loaded")||(g.mF(b,"loaded","true"),g.jG(a),g.jE(g.Fa(YCa,a),0))}))},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},rDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?sDa(a.shift(),function(){z6(a)}):A6()},tDa=function(a){return"chrome-extension://"+a+B6},sDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=rDa();
a&&a(!1,"No cast extension found")},D6=function(){if(uDa){var a=2,b=rDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;sDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},vDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},wDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Bd=b;this.D=(0,g.B)(this.tL,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.Ym(this);this.A=new g.Cg;this.A.setInterval(250)},yDa=function(a,b,c){a.vk=1;
a.Ph=i6(b.clone());a.zj=c;a.D=!0;xDa(a,null)},H6=function(a,b,c,d,e){a.vk=1;
a.Ph=i6(b.clone());a.zj=null;a.D=c;e&&(a.CF=!1);xDa(a,d)},xDa=function(a,b){a.ol=(0,g.H)();
I6(a);a.ti=a.Ph.clone();j6(a.ti,"t",a.F);a.Sn=0;a.Uc=a.o.kt(a.o.Jn()?b:null);0<a.Yt&&(a.Rq=new g.hl((0,g.B)(a.TG,a,a.Uc),a.Yt));a.Z.X(a.Uc,"readystatechange",a.IW);var c=a.Zi?g.dc(a.Zi):{};a.zj?(a.Lr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Uc.send(a.ti,a.Lr,a.zj,c)):(a.Lr="GET",a.CF&&!g.Jd&&(c.Connection="close"),a.Uc.send(a.ti,a.Lr,null,c));a.o.If(1)},BDa=function(a,b,c){for(var d=!0;!a.Mi&&a.Sn<c.length;){var e=zDa(a,c);
if(e==J6){4==b&&(a.Qh=4,K6(15),d=!1);break}else if(e==ADa){a.Qh=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Qh=1,K6(17),d=!1);a.Pf=a.Pf&&d;d||(M6(a),N6(a))},zDa=function(a,b){var c=a.Sn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return ADa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.Sn=d+c;return e},DDa=function(a,b){a.ol=(0,g.H)();
I6(a);var c=b?window.location.hostname:"";a.ti=a.Ph.clone();g.Rm(a.ti,"DOMAIN",c);g.Rm(a.ti,"t",a.F);try{a.Qf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Qh=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in CDa)k=O6[l]=CDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.Bc("b/12014412"),d+"</body></html>");a.Qf.open();a.Qf.write(g.bd(c));a.Qf.close();a.Qf.parentWindow.m=(0,g.B)(a.QV,a);a.Qf.parentWindow.d=(0,g.B)(a.JE,a,!0);a.Qf.parentWindow.rpcClose=(0,g.B)(a.JE,a,!1);c=a.Qf.createElement("DIV");a.Qf.parentWindow.document.body.appendChild(c);d=g.Pc(a.ti.toString());d=g.rb(g.Mc(d));d=g.kd(g.Bc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.hd(c,g.bd(d));a.o.If(1)},
I6=function(a){a.Ex=(0,g.H)()+a.C;
EDa(a,a.C)},EDa=function(a,b){if(null!=a.Fl)throw Error("WatchDog timer not null");
a.Fl=P6((0,g.B)(a.gW,a),b)},Q6=function(a){a.Fl&&(g.x.clearTimeout(a.Fl),a.Fl=null)},N6=function(a){a.o.MA()||a.Mi||a.o.Bq(a)},M6=function(a){Q6(a);
g.lf(a.Rq);a.Rq=null;a.A.stop();g.dn(a.Z);if(a.Uc){var b=a.Uc;a.Uc=null;b.abort();b.dispose()}a.Qf&&(a.Qf=null)},L6=function(a,b){try{a.o.BE(a,b),a.o.If(4)}catch(c){}},GDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;FDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){GDa(a,b,c,d,f)},f)})}},FDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},HDa=function(a){this.o=a;
this.A=new F6},IDa=function(a){var b=S6(a.o,a.Ql,"/mail/images/cleardot.gif");
i6(b);GDa(b.toString(),5E3,(0,g.B)(a.yK,a),3,2E3);a.If(1)},U6=function(a){var b=a.o.J;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Ie=new G6(a,void 0,void 0,void 0),a.Ie.Zi=a.Wt,b=a.o,b=S6(b,b.Jn()?a.Em:null,a.Xt),K6(5),!g.Hd||g.tc(10))j6(b,"TYPE","xmlhttp"),H6(a.Ie,b,!1,a.Em,!1);else{j6(b,"TYPE","html");var c=a.Ie;a=!!a.Em;c.vk=3;c.Ph=i6(b.clone());DDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},JDa=function(a,b){this.o=a;
this.map=b;this.context=null},KDa=function(a){g.nf.call(this,"statevent",a)},LDa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},MDa=function(a){g.nf.call(this,"serverreachability",a)},PDa=function(a){NDa(a);
if(3==a.o){var b=a.un++,c=a.ip.clone();g.Rm(c,"SID",a.B);g.Rm(c,"RID",b);g.Rm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.vk=2;b.Ph=i6(c.clone());(new window.Image).src=b.Ph;b.ol=(0,g.H)();I6(b)}ODa(a)},QDa=function(a){a.UK(1,0);
a.ip=S6(a,null,a.Vt);X6(a)},NDa=function(a){a.Bh&&(a.Bh.abort(),a.Bh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Ig&&(g.x.clearTimeout(a.Ig),a.Ig=null);Y6(a);a.je&&(a.je.cancel(),a.je=null);a.Hh&&(g.x.clearTimeout(a.Hh),a.Hh=null)},RDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new JDa(a.ER++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.je||a.Hh||(a.Hh=P6((0,g.B)(a.HE,a),0),a.jk=0)},TDa=function(a,b){if(1==a.o){if(!b){a.un=Math.floor(1E5*Math.random());
var c=a.un++,d=new G6(a,"",c,void 0);d.Zi=null;var e=Z6(a),f=a.ip.clone();g.Rm(f,"RID",c);g.Rm(f,"CVER","1");W6(a,f);yDa(d,f,e);a.je=d;a.o=2}}else 3==a.o&&(b?SDa(a,b):0==a.A.length||a.je||SDa(a))},SDa=function(a,b){if(b)if(6<a.Oi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.un-1;var d=Z6(a)}else c=b.G,d=b.zj;else c=a.un++,d=Z6(a);var e=a.ip.clone();g.Rm(e,"SID",a.B);g.Rm(e,"RID",c);g.Rm(e,"AID",a.Jk);W6(a,e);c=new G6(a,a.B,c,a.jk+1);c.Zi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.je=c;yDa(c,e,d)},W6=function(a,b){if(a.Ad){var c=a.Ad.sA();
c&&g.Jb(c,function(a,c){g.Rm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Oi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Oi?e:f-d;try{g.Jb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},UDa=function(a){a.Ac||a.Ig||(a.G=1,a.Ig=P6((0,g.B)(a.GE,a),0),a.Wj=0)},$6=function(a){if(a.Ac||a.Ig||3<=a.Wj)return!1;
a.G++;a.Ig=P6((0,g.B)(a.GE,a),VDa(a,a.Wj));a.Wj++;return!0},T6=function(a,b,c){a.Jr=c;
a.hg=b.Vg;a.F||QDa(a)},Y6=function(a){null!=a.Pi&&(g.x.clearTimeout(a.Pi),a.Pi=null)},VDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Ad&&(c=null);var d=(0,g.B)(a.zX,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),i6(c));FDa(c.toString(),1E4,d)}else K6(2);WDa(a,b)},WDa=function(a,b){a.o=0;
a.Ad&&a.Ad.uz(b);ODa(a);NDa(a)},ODa=function(a){a.o=0;
a.hg=-1;if(a.Ad)if(0==a.C.length&&0==a.A.length)a.Ad.Rs();else{g.Xa(a.C);var b=g.Xa(a.A);a.C.length=0;a.A.length=0;a.Ad.Rs(b)}},S6=function(a,b,c){var d=g.Sm(c);
if(""!=d.A)b&&g.Km(d,b+"."+d.A),g.Lm(d,d.D);else{var e=window.location;d=WCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.jm&&g.Jb(a.jm,function(a,b){g.Rm(d,b,a)});
g.Rm(d,"VER",a.Oi);W6(a,d);return d},P6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new KDa(b7,a))},XDa=function(){},YDa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.mu(this.HV,0,this);g.N(this,this.o);this.Bd=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.B)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.jD;this.A=new c7(this.jY,this);this.o=this.ib=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},ZDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Jr,sessionId:a.o.B,arrayId:a.o.Jk}},$Da=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&TDa(a.o),PDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},aEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Sg(a)||"";b&&(this.port=":"+b);this.domain=g.Rg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.ah(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Fd:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.AE(b,a)},eEa=function(){var a=bEa;
cEa();i7.push(a);dEa(i7)},j7=function(a,b){cEa();
var c=i7,d=fEa(a,String(b));g.Pa(c)?gEa(d):(dEa(c),(0,g.D)(c,function(a){a(d)}))},cEa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},gEa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},dEa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},fEa=function(a,b){var c=((0,g.H)()-hEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.VF.call(this);
this.G=a;this.o=[]},iEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},jEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ud)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=iEa(a,b[d])||c;return c},kEa=function(a,b){var c=a.o.length;
a.o=(0,g.Ud)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.VF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},lEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.HL,a),(0,g.B)(a.GL,a))}},p7=function(a){var b=dDa(jDa());
b=(0,g.Ud)(b,function(a){return!a.uuid});
return jEa(a,b)},r7=function(a,b){lDa((0,g.I)(a.o,bDa));
b&&kDa()},t7=function(a,b){g.VF.call(this);
this.F=b;var c=g.gH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Jg(this.o))},mEa=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.o))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Jg(a.o)),a.o=b,a.V("screenChange"));nEa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.lE(a.B);
a.B=g.jE((0,g.B)(a.Kw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},oEa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},nEa=function(a){a=g.Rb(g.Kb(a.o,function(a){return a}));
g.fb(a);a.length?g.fH("yt-remote-online-screen-ids",a.join(","),60):g.hH("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};pEa(this)},rEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Be();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);mEa(a.A,l,function(a){e(a?l:null)})}else c?qEa(a,c,(0,g.B)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));mEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},sEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},qEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.AE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},tEa=function(a){a.o=a.B.Be();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},pEa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.VL,a));tEa(a);a.C=dDa(g.gH("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.B)(a.Be,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.fH("yt-remote-automatic-screen-cache",(0,g.I)(a.C,bDa)));y7(a);a.D[b.uuid]=b.id;g.fH("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.gH("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.VF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},A7=function(a,b){j7(a.M,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.pY,this);this.D=(0,g.B)(this.sW,this);this.C=g.jE((0,g.B)(function(){uEa(this,null)},this),12E4)},vEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Jg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.B)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Jg(b))},uEa=function(a,b){g.lE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Cq,a),d=(0,g.B)(a.He,a);a.CA(b,c,d,5)}}else a.He(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.B)(this.sY,this);this.o=g.z},wEa=function(a){a.o=a.J.aH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.z;
this.Cq(a)},a),(0,g.B)(function(a){this.o=g.z;
this.He(a)},a))},xEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}nDa()&&(b.env_useStageMdx=1);return g.Zg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.jE((0,g.B)(this.Lk,this,null),150)},E7=function(a,b,c,d){g.VF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.TU,this)},yEa=function(a,b){return b?g.Ka(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},bEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.lf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.EE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Lk(null)):a.V("yt-remote-cast2-session-change",null))},zEa=function(a){var b=a.A.ZG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=yEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},FEa=function(a,b,c,d,e,f,k){AEa()?BEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?CEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?CEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.hH("yt-remote-cast-available"),g.hH("yt-remote-cast-receiver"),DEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):qDa():C6("CriOS")?vDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?wDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(EEa.map(tDa))):A6())):I7("Cannot initialize because not running Chrome")},DEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);GEa(!1);g.hG(N7);N7.length=0},O7=function(){return!!g.gH("yt-remote-cast-installed")},HEa=function(){var a=g.gH("yt-remote-cast-receiver");
return a?a.friendlyName:null},IEa=function(){I7("clearCurrentReceiver");
g.hH("yt-remote-cast-receiver")},JEa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.gG("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},AEa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.wI||a},KEa=function(a,b){M7().init(a,b)},BEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.fH("yt-remote-cast-available",a);g.kG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.fH("yt-remote-cast-receiver",a);g.kG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.fH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.hH("yt-remote-cast-receiver");g.kG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},CEa=function(a,b){L7(!0);
J7(!1);KEa(a,function(a){a?(GEa(!0),g.jG("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.hH("yt-remote-cast-available"),g.hH("yt-remote-cast-receiver"),DEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.fH("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},GEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.lg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.lg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.rb()?((0,g.H)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.H)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ec(a.A);b.hasPrevious=a.lg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.VF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.zC;this.B=this.A=null;this.J=(0,g.B)(this.nS,this);this.G=(0,g.B)(this.xn,this);this.H=(0,g.B)(this.mS,this);this.K=(0,g.B)(this.zS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Lx,this),LEa(this))):c=3;0!=c&&(b?this.Lx(c):g.jE((0,g.B)(function(){this.Lx(c)},this),0));
var d=JEa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},LEa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.OU,a),this))},a)},MEa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.Bc()&&g.BC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){MEa(a);
a.C.setPlayerContextData(Y7(b));LEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.xn(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.xn(a.B.media[0]))},NEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.B)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.VF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.W=[];this.C=this.G=this.B=this.jb=this.o=null;this.ua=a;this.W.push(g.EF(window,"beforeunload",(0,g.B)(this.xL,this)));this.A=[];this.jb=new S7;this.ca=b.id;this.o=OEa(this,c);this.o.subscribe("handlerOpened",this.rS,this);this.o.subscribe("handlerClosed",this.oS,this);this.o.subscribe("handlerError",this.pS,this);this.o.subscribe("handlerMessage",this.qS,this);aEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.jb.videoId;g.iH()&&g.fH("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},OEa=function(a,b){return new d7(g7(a.ua,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},PEa=function(a){a.D=g.jE((0,g.B)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.lE(a.D);
a.D=window.NaN},k8=function(a){g.lE(a.M);
a.M=window.NaN},QEa=function(a){l8(a);
a.L=g.jE((0,g.B)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.lE(a.L);
a.L=window.NaN},SEa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.aa()&&a.jb.reset(),i8(a,1),m8(a,"getNowPlaying"),REa(a)):a.F(1)},TEa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jb.videoId&&(g.Zb(b.params)?a.jb.A=null:a.jb.A=b.params,a.V("remotePlayerChange"))},UEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.jb.listId=b.params.listId||a.jb.listId;X7(a.jb,c,d);a.V("remoteQueueChange")},WEa=function(a,b){b.params=b.params||{};
UEa(a,b);VEa(a,b);a.V("autoplayDismissed")},VEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.jb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.jb.o&&(c=-1E3);a.jb.o=c;c=Number(b.params.loadedTime);a.jb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.jb.J=(0,window.isNaN)(c)?0:c;c=a.jb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.jb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.jb.o?QEa(a):l8(a);
a.V("remotePlayerChange")},XEa=function(a,b){if(-1E3!=a.jb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.jb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},YEa=function(a,b){var c="true"==b.params.muted;
a.jb.volume=(0,window.parseInt)(b.params.volume,10);a.jb.muted=c;a.V("remotePlayerChange")},ZEa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},$Ea=function(a,b){var c="true"==b.params.hasNext;
a.jb.lg="true"==b.params.hasPrevious;a.jb.hasNext=c;a.V("previousNextChange")},REa=function(a){g.lE(a.K);
a.K=g.jE((0,g.B)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Jg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.kd=a;this.A=[];this.A.push(this.kd.$_s("screenChange",(0,g.B)(this.nY,this)));this.A.push(this.kd.$_s("onlineScreenChange",(0,g.B)(this.oU,this)))},eFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.dE("MDX_CONFIG")||b;fDa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),nDa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));aFa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);FEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.kG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Jg(b)),t8.push(g.gG("yt-remote-cast2-availability-change",function(){g.kG("yt-remote-receiver-availability-change")})),t8.push(g.gG("yt-remote-cast2-receiver-selected",function(){u8(null);
g.kG("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.gG("yt-remote-cast2-receiver-resumed",function(){g.kG("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.gG("yt-remote-cast2-session-change",bFa)),t8.push(g.gG("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),IEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.aG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Jg(a)),cFa(a),c.start(),r8()||dFa())},gFa=function(){var a=fFa();
O7()&&g.gH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},fFa=function(){var a=q8().kd.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return eDa(a)},z8=function(){var a=hFa();
!a&&O7()&&HEa()&&(a={key:"cast-selector-receiver",name:HEa()});return a},hFa=function(){var a=fFa(),b=x8();
b||(b=v8());return g.Ka(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Be();return r6(b,a)},bFa=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},iFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},jFa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||iFa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.D)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.kG("yt-remote-connection-change",!1):!b&&a&&g.kG("yt-remote-connection-change",!0)},v8=function(){var a=g.iH();
if(!a)return null;var b=q8().Be();return r6(b,a)},B8=function(a,b){x8()&&x8();
iFa(a.id);var c=new g8(o8,a,w8());c.connect(b,jFa());c.subscribe("beforeDisconnect",function(a){g.kG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},dFa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),IEa(),s8("Skipping connecting because no session screen found."))},aFa=function(){var a=w8();
if(g.Zb(a)){a=u6();var b=g.gH("yt-remote-session-name")||"",c=g.gH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},cFa=function(a){a?(g.fH("yt-remote-session-app",a.app),g.fH("yt-remote-session-name",a.name)):(g.hH("yt-remote-session-app"),g.hH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.G=a;this.T=b;this.A=new g.SF(this);g.N(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.GT);this.A.R(b,"captionschanged",this.lS);this.A.R(b,"captionssettingschanged",this.lG);this.A.R(b,"videoplayerreset",this.Dq);this.A.R(b,"mdxautoplaycancel",this.xK);this.O=this.A.R(b,"onVolumeChange",this.lE);this.F=!1;this.o=c;c.subscribe("proxyStateChange",this.AE,this);c.subscribe("remotePlayerChange",this.An,this);c.subscribe("remoteQueueChange",this.Dq,this);c.subscribe("autoplayUpNext",this.WD,
this);c.subscribe("previousNextChange",this.xE,this);c.subscribe("nowAutoplaying",this.oE,this);c.subscribe("autoplayDismissed",this.VD,this);this.suggestion=null;this.H=new g.VP(64);this.B=new g.mu(this.hG,500,this);g.N(this,this.B);this.C=new g.mu(this.iG,1E3,this);g.N(this,this.C);this.K=new E6(this.OX,0,this);g.N(this,this.K);this.D={};this.L=new g.mu(this.HG,1E3,this);g.N(this,this.L);this.J=new g.hl(this.rQ,1E3,this);g.N(this,this.J);this.M=g.z;this.lG();this.Dq();this.An()},G8=function(a,b){var c=
a.G,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},kFa=function(a){G8(a,0);
a.B.stop();H8(a,new g.VP(64))},J8=function(a,b){if(I8(a)&&!a.F){var c=null;
b&&(c={style:a.T.sj()},g.gc(c,b));a.o.WF(a.T.getVideoData(1).videoId,c);a.D=a8(a.o).A}},K8=function(a,b){var c=a.T.tg();
if(c){var d=c.ze();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Ek;f=VCa(f);var n=a8(c);l=l||0;var p={videoId:k,currentIndex:l};X7(n,k,l);g.u(b)&&(V7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Jg(f));e8(c,"setPlaylist",p);e||c8(c,n);H8(a,new g.VP(1))},lFa=function(a,b){if(b){var c=a.T.Ec("captions","tracklist",{wB:1});
c&&c.length?(a.T.Ud("captions","track",b),a.F=!1):(a.T.Tk("captions"),a.F=!0)}else a.T.Ud("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.T.getVideoData(1).videoId},H8=function(a,b){a.C.stop();
var c=a.H;if(!g.$P(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.gU(a.T,d);a.H=b;mFa(a.G,c,b)}},L8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Cqa()]},{I:"div",N:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.gV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);nFa(this,g.bU(a))},nFa=function(a,b){if(3==a.C.Sa()){var c={RECEIVER_NAME:a.C.Ec("remote","currentReceiver").name};
c=g.X(b,128)?g.f0("Terjadi error pada $RECEIVER_NAME",c):b.rb()||g.X(b,4)?g.f0("Diputar di $RECEIVER_NAME",c):g.f0("Terhubung ke $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.DY.call(this,"Diputar di",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},N8=function(a){g.HU.call(this,a);
this.B={key:p6(),name:"Komputer ini"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.VP(64);this.J=0;if(!g.ZM(g.Y(this.o))){a=this.o;var b=g.YH(a);b&&(b=b.Xm())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.xU(a,b.element,4)}},mFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.eQ(c,b))},O8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)A8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.tg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Yb(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ek,index:Math.max(a.o.zC(),0),currentTime:0==f?void 0:f};(d=VCa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Jg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||null):
K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.kG("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().Be(),(d=r6(d,b.key))&&B8(d,1))}},CDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},oFa={},aDa={CZ:"atp",j4:"ska",y3:"que",K2:"mus",f4:"sus",M0:"dsp"};
k6.prototype.Mo=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",uDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),EEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(E6,g.M);g.h=E6.prototype;g.h.sL=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Bd:this.Ea=g.Dg(this.D,this.Bd)};
g.h.stop=function(){this.Ea&&(g.Eg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.Y=function(){this.stop();E6.fa.Y.call(this)};
g.h.tL=function(){this.B?(this.Ea=g.Dg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.Zi=null;g.h.Pf=!1;g.h.Fl=null;g.h.Ex=null;g.h.ol=null;g.h.vk=null;g.h.Ph=null;g.h.ti=null;g.h.zj=null;g.h.Uc=null;g.h.Sn=0;g.h.Qf=null;g.h.Lr=null;g.h.Qh=null;g.h.Fm=-1;g.h.CF=!0;g.h.Mi=!1;g.h.Yt=0;g.h.Rq=null;var ADa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.IW=function(a){a=a.target;var b=this.Rq;b&&3==g.wx(a)?b.Bm():this.TG(a)};
g.h.TG=function(a){try{if(a==this.Uc)a:{var b=g.wx(this.Uc),c=this.Uc.A,d=this.Uc.getStatus();if(g.Hd&&!g.tc(10)||g.Jd&&!g.sc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.Ax(this.Uc))break a;this.Mi||4!=b||7==c||(8==c||0>=d?this.o.If(3):this.o.If(2));Q6(this);var e=this.Uc.getStatus();this.Fm=e;var f=g.Ax(this.Uc);(this.Pf=200==e)?(4==b&&M6(this),this.D?(BDa(this,b,f),g.pf&&this.Pf&&3==b&&(this.Z.X(this.A,"tick",this.EW),this.A.start())):L6(this,f),this.Pf&&!this.Mi&&(4==b?this.o.Bq(this):
(this.Pf=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Qh=3,K6(13)):(this.Qh=0,K6(14)),M6(this),N6(this))}}catch(k){this.Uc&&g.Ax(this.Uc)}finally{}};
g.h.EW=function(){var a=g.wx(this.Uc),b=g.Ax(this.Uc);this.Sn<b.length&&(Q6(this),BDa(this,a,b),this.Pf&&4!=a&&I6(this))};
g.h.QV=function(a){P6((0,g.B)(this.PV,this,a),0)};
g.h.PV=function(a){this.Mi||(Q6(this),L6(this,a),I6(this))};
g.h.JE=function(a){P6((0,g.B)(this.OV,this,a),0)};
g.h.OV=function(a){this.Mi||(M6(this),this.Pf=a,this.o.Bq(this),this.o.If(4))};
g.h.cancel=function(){this.Mi=!0;M6(this)};
g.h.gW=function(){this.Fl=null;var a=(0,g.H)();0<=a-this.Ex?(2!=this.vk&&this.o.If(3),M6(this),this.Qh=2,K6(18),N6(this)):EDa(this,this.Ex-a)};g.h=HDa.prototype;g.h.Wt=null;g.h.Ie=null;g.h.Sq=!1;g.h.NA=null;g.h.ep=null;g.h.Ru=null;g.h.Xt=null;g.h.af=null;g.h.Vg=-1;g.h.Em=null;g.h.Ql=null;g.h.connect=function(a){this.Xt=a;a=S6(this.o,null,this.Xt);K6(3);this.NA=(0,g.H)();var b=this.o.H;null!=b?(this.Em=b[0],(this.Ql=b[1])?(this.af=1,IDa(this)):(this.af=2,U6(this))):(j6(a,"MODE","init"),this.Ie=new G6(this,void 0,void 0,void 0),this.Ie.Zi=this.Wt,H6(this.Ie,a,!1,null,!0),this.af=0)};
g.h.yK=function(a){if(a)this.af=2,U6(this);else{K6(4);var b=this.o;b.hg=b.Bh.Vg;a7(b,9)}a&&this.If(2)};
g.h.kt=function(a){return this.o.kt(a)};
g.h.abort=function(){this.Ie&&(this.Ie.cancel(),this.Ie=null);this.Vg=-1};
g.h.MA=function(){return!1};
g.h.BE=function(a,b){this.Vg=a.Fm;if(0==this.af)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.hg=this.Vg;a7(c,2);return}this.Em=c[0];this.Ql=c[1]}else c=this.o,c.hg=this.Vg,a7(c,2);else if(2==this.af)if(this.Sq)K6(7),this.Ru=(0,g.H)();else if("11111"==b){if(K6(6),this.Sq=!0,this.ep=(0,g.H)(),c=this.ep-this.NA,!g.Hd||g.tc(10)||500>c)this.Vg=200,this.Ie.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.ep=this.Ru=(0,g.H)(),this.Sq=!1};
g.h.Bq=function(){this.Vg=this.Ie.Fm;if(this.Ie.Pf)0==this.af?this.Ql?(this.af=1,IDa(this)):(this.af=2,U6(this)):2==this.af&&((!g.Hd||g.tc(10)?!this.Sq:200>this.Ru-this.ep)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.af?K6(9):2==this.af&&K6(10);var a=this.o;a.hg=this.Vg;a7(a,2)}};
g.h.Jn=function(){return this.o.Jn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.If=function(a){this.o.If(a)};g.h=V6.prototype;g.h.jm=null;g.h.je=null;g.h.Ac=null;g.h.Vt=null;g.h.ip=null;g.h.iz=null;g.h.xp=null;g.h.un=0;g.h.ER=0;g.h.Ad=null;g.h.Hh=null;g.h.Ig=null;g.h.Pi=null;g.h.Bh=null;g.h.Jr=null;g.h.Jk=-1;g.h.LB=-1;g.h.hg=-1;g.h.jk=0;g.h.Wj=0;g.h.Oi=8;var b7=new g.Of;g.C(KDa,g.nf);g.C(LDa,g.nf);g.C(MDa,g.nf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.Vt=b;this.jm=c||{};d&&g.u(e)&&(this.jm.OSID=d,this.jm.OAID=e);this.F?(P6((0,g.B)(this.Fz,this,a),100),QDa(this)):this.Fz(a)};
g.h.Fz=function(a){this.Bh=new HDa(this);this.Bh.Wt=null;this.Bh.A=this.D;this.Bh.connect(a)};
g.h.MA=function(){return 0==this.o};
g.h.HE=function(a){this.Hh=null;TDa(this,a)};
g.h.GE=function(){this.Ig=null;this.Ac=new G6(this,this.B,"rpc",this.G);this.Ac.Zi=null;this.Ac.Yt=0;var a=this.iz.clone();g.Rm(a,"RID","rpc");g.Rm(a,"SID",this.B);g.Rm(a,"CI",this.Jr?"0":"1");g.Rm(a,"AID",this.Jk);W6(this,a);if(!g.Hd||g.tc(10))g.Rm(a,"TYPE","xmlhttp"),H6(this.Ac,a,!0,this.xp,!1);else{g.Rm(a,"TYPE","html");var b=this.Ac,c=!!this.xp;b.vk=3;b.Ph=i6(a.clone());DDa(b,c)}};
g.h.BE=function(a,b){if(0!=this.o&&(this.Ac==a||this.je==a))if(this.hg=a.Fm,this.je==a&&3==this.o)if(7<this.Oi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Ig){if(this.Ac)if(this.Ac.ol+3E3<this.je.ol)Y6(this),this.Ac.cancel(),this.Ac=null;else break a;$6(this);K6(19)}}else this.LB=c[1],0<this.LB-this.Jk&&37500>c[2]&&this.Jr&&0==this.Wj&&!this.Pi&&(this.Pi=P6((0,g.B)(this.gS,this),6E3));else a7(this,11)}else b!=oFa.F_.o&&a7(this,11);else if(this.Ac==a&&
Y6(this),!g.F(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.Jk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.xp=e[2],e=e[3],null!=e?this.Oi=e:this.Oi=6,this.o=3,this.Ad&&this.Ad.wz(),this.iz=S6(this,this.Jn()?this.xp:null,this.Vt),UDa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Ad&&this.Ad.vz(e),this.Wj=0)}}};
g.h.gS=function(){null!=this.Pi&&(this.Pi=null,this.Ac.cancel(),this.Ac=null,$6(this),K6(20))};
g.h.Bq=function(a){if(this.Ac==a){Y6(this);this.Ac=null;var b=2}else if(this.je==a)this.je=null,b=1;else return;this.hg=a.Fm;if(0!=this.o)if(a.Pf)1==b?(b=(0,g.H)()-a.ol,b7.dispatchEvent(new LDa(b7,a.zj?a.zj.length:0,b,this.jk)),X6(this),this.C.length=0):UDa(this);else{var c=a.Qh,d;if(!(d=3==c||7==c||0==c&&0<this.hg)){if(d=1==b)this.je||this.Hh||1==this.o||2<=this.jk?d=!1:(this.Hh=P6((0,g.B)(this.HE,this,a),VDa(this,this.jk)),this.jk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.UK=function(a){if(!g.Oa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.zX=function(a){a?K6(2):(K6(1),WDa(this,8))};
g.h.kt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.qx;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ad&&this.Ad.isActive(this)};
g.h.If=function(a){b7.dispatchEvent(new MDa(b7,a))};
g.h.Jn=function(){return!(!g.Hd||g.tc(10))};
g.h=XDa.prototype;g.h.wz=function(){};
g.h.vz=function(){};
g.h.uz=function(){};
g.h.Rs=function(){};
g.h.sA=function(){return{}};
g.h.isActive=function(){return!0};g.C(c7,g.M);g.h=c7.prototype;g.h.HV=function(){this.Bd=Math.min(3E5,2*this.Bd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Bd+15E3*Math.random();g.nu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Bd=5E3};g.C(d7,XDa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ae=function(a){return this.B.ae(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.lf(this.B),$Da(this),g.lf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Ad=null);d.Ad=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Jk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.gc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&RDa(this.o,c)};
g.h.wz=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)RDa(this.o,a[b])}this.V("handlerOpened")};
g.h.uz=function(a){var b=2==a&&401==this.o.hg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Rs=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.sA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.gc(a,this.D);return a};
g.h.vz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),PDa(this.o)):this.V("handlerMessage",new YDa(a[0],a[1]))};
g.h.jY=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.je&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var hEa=(0,g.H)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.C(n7,g.VF);n7.prototype.Be=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.C(o7,g.VF);var pFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.YG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.lE(this.Ea),this.Ea=window.NaN)};
g.h.Y=function(){this.stop();o7.fa.Y.call(this)};
g.h.YG=function(){this.Ea=window.NaN;this.o=g.AE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.lY,this),onError:(0,g.B)(this.kY,this),Fd:(0,g.B)(this.mY,this)})};
g.h.lY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.kY=function(a){this.o=null;a.status&&404==a.status?this.A>=pFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=pFa[this.A],this.Ea=g.jE((0,g.B)(this.YG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.mY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.gH("yt-remote-lounge-token-expiration")&&lEa(this);g.lE(this.A);this.A=g.jE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);iEa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||lEa(this)};
g.h.remove=function(a,b){var c=p7(this);kEa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Dr=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.Y=function(){g.lE(this.A);q7.fa.Y.call(this)};
g.h.HL=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.GL=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.C(t7,g.VF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.gH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?v7(this):(this.C=(0,g.H)()+3E5,g.fH("yt-remote-fast-check-period",this.C),this.Kw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Kb(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.Y=function(){g.lE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.fa.Y.call(this)};
g.h.Kw=function(){g.lE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=oEa(this);if(g.Ob(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Rb(a).join(",")},(0,g.B)(this.oV,this,a),(0,g.B)(this.nV,this))}else u7(this,{}),v7(this)};
g.h.oV=function(a,b){this.A=null;var c=g.Rb(oEa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.hc("Changing Screen set during request."),this.Kw()};
g.h.nV=function(a){this.hc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.hc=function(a){j7("OnlineScreenService",a)};g.C(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Dr=function(a,b,c,d){this.B.contains(a)?this.B.Dr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.Be=function(a){return a?this.o:g.Wa(this.o,(0,g.Ud)(this.C,function(a){return!this.contains(a)},this))};
g.h.ZG=function(){return(0,g.Ud)(this.Be(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.aH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.lf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.lf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.oY=function(a,b,c,d){g.AE(g7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new l6(d.screen||{});if(!e.name||sEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);sEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Fd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.lf(this.B);g.lf(this.A);w7.fa.Y.call(this)};
g.h.VL=function(){tEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.C(z7,g.VF);g.h=z7.prototype;g.h.Cq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.He=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.M,a)};
g.h.cH=function(){return null};
g.h.Qw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Qw("");z7.fa.Y.call(this)};g.C(B7,z7);g.h=B7.prototype;g.h.Pw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);vEa(this)};
g.h.Lk=function(a){this.info("launchWithParams no-op for Cast: "+g.Jg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.He()},this),(0,g.B)(function(){this.He(Error("Failed to stop receiver app."))},this)):this.He(Error("Stopping cast device witout session."))};
g.h.Qw=g.z;g.h.Y=function(){this.info("disposeInternal");g.lE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.fa.Y.call(this)};
g.h.sW=function(a,b){if(!this.la())if(b){var c=g.kx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Jg(c));switch(d){case "mdxSessionStatus":uEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.CA=function(a,b,c,d){rEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.jE((0,g.B)(this.CA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.cH=function(){return this.o};
g.h.pY=function(a){this.la()||a||(A7(this,"Cast session died."),this.He())};g.C(C7,z7);g.h=C7.prototype;g.h.Pw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Lk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.lE(this.F);this.C?this.C.stop((0,g.B)(this.He,this,null),(0,g.B)(this.He,this,"Failed to stop DIAL device.")):this.He()};
g.h.Y=function(){this.o();this.o=g.z;g.lE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.fa.Y.call(this)};
g.h.sY=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.z,this.He())};
g.h.Eu=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,xEa(this));a(b);wEa(this)}else this.G=(0,g.B)(function(){g.lE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,xEa(this));a(b);wEa(this)},this),this.F=g.jE((0,g.B)(function(){this.G()},this),100)};
g.h.jN=function(a,b,c){rEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Cq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Eu(b,c)},this),(0,g.B)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.Eu(b,c)},this))};g.C(D7,z7);D7.prototype.stop=function(){this.He()};
D7.prototype.Pw=g.z;D7.prototype.Lk=function(){g.lE(this.o);this.o=window.NaN;var a=r6(this.J.Be(),this.A.label);a?this.Cq(a):this.He(Error("No such screen"))};
D7.prototype.Y=function(){g.lE(this.o);this.o=window.NaN;D7.fa.Y.call(this)};g.C(E7,g.VF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.DE,this),(0,g.B)(this.XU,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.QS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),eEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.bH,this)),this.B=zEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.hc("Failed to set initial custom receivers: "+g.Jg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.B)(function(a){this.hc("Failed to initialize API: "+g.Jg(a));
b(!1)},this))};
g.h.hX=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.Be(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=yEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(a){this.hc("Failed to set initial custom receivers: "+g.Jg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.Qw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.iX=function(a){this.la()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.Lk(a):this.hc("Setting connection data without a session")};
g.h.rY=function(){this.la()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.DE,this),(0,g.B)(this.sV,this))};
g.h.Y=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.bH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],bEa);g.lf(this.o);E7.fa.Y.call(this)};
g.h.hc=function(a){j7("Controller",a)};
g.h.EE=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.TU=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.QS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.jN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Eu,b))};
g.h.DE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.Be(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.lf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.EE,this,this.o)),this.o.Lk(null));this.o.Pw(a)}}};
g.h.qY=function(){return this.o?this.o.cH():null};
g.h.sV=function(a){this.la()||(this.hc("Failed to estabilish a session: "+g.Jg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.XU=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.bH=function(){this.la()||(this.B=zEa(this),F7("Updating custom receivers: "+g.Jg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.B)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.iX;E7.prototype.setConnectedScreenStatus=E7.prototype.hX;E7.prototype.stopSession=E7.prototype.rY;E7.prototype.getCastSession=E7.prototype.qY;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.lg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.rb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+U7(this):this.J};
g.h.clone=function(){return new S7(Y7(this))};g.C($7,g.VF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.XG=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.rb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Fa(this.XG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Fa(this.setVolume,a,b))};
g.h.WF=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Jg(b.style),g.gc(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Fa(this.WF,a,b))};
g.h.Kx=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Kb.id});var c=a8(this);c.audioTrackId=b.Kb.id;c8(this,c)}else b8(this,g.Fa(this.Kx,a,b))};
g.h.WG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Fa(this.WG,a,b))};
g.h.VG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Fa(this.VG,a,b))};
g.h.Xz=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.Xz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.fa.dispose.call(this)};
g.h.Y=function(){MEa(this);this.C=null;this.D.clear();Z7(this,null);$7.fa.Y.call(this)};
g.h.Lx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.CC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.OU=function(a,b){this.V(a,b)};
g.h.nS=function(a){if(!a)this.xn(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.xn=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),NEa(this),this.V("remotePlayerChange")};
g.h.mS=function(a){a?(NEa(this),this.V("remotePlayerChange")):this.xn(null)};
g.h.zS=function(){var a=JEa();a&&Z7(this,a)};
g.h.hc=function(a){j7("CP",a)};g.C(g8,g.VF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.jb.listId=c);this.jb.videoId=d;this.jb.index=k||0;this.jb.state=3;V7(this.jb,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Jg(l));this.o.connect({method:"setPlaylist",
params:g.Jg(l)},a,iDa())}else h8("Connecting without params"),this.o.connect({},a,iDa());PEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.fa.dispose.call(this)};
g.h.Y=function(){j8(this);l8(this);k8(this);g.lE(this.J);this.J=window.NaN;g.lE(this.K);this.K=window.NaN;this.B=null;g.FF(this.W);this.W.length=0;this.o.dispose();g8.fa.Y.call(this);this.C=this.G=this.A=this.jb=this.o=null};
g.h.xL=function(){this.F(2)};
g.h.rS=function(){h8("Channel opened");this.O&&(this.O=!1,k8(this),this.M=g.jE((0,g.B)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
mDa(ZDa(this.o),this.ca)};
g.h.oS=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.pS=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.qS=function(a){a.params?h8("Received: action="+a.action+", params="+g.Jg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.kx(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.Ka(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
SEa(this,a);break;case "loungeScreenDisconnected":g.Va(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
SEa(this,!1);break;case "remoteConnected":var b=new k6(g.kx(a.params.device));g.Ka(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new k6(g.kx(a.params.device));g.Va(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":UEa(this,a);break;case "nowPlaying":WEa(this,a);break;case "onStateChange":VEa(this,a);break;case "onAdStateChange":XEa(this,a);break;case "onVolumeChanged":YEa(this,a);break;case "onSubtitlesTrackChanged":TEa(this,a);break;case "nowAutoplaying":ZEa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":$Ea(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.TW=function(){if(this.B){var a=this.B;this.B=null;this.jb.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.ae;g8.prototype.ka=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ka;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();$Da(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ia=function(){var a=this.jb;this.B&&(a=this.jb.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ia;
g8.prototype.pa=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.jb.videoId&&(this.B=b.videoId,g.lE(this.J),this.J=g.jE((0,g.B)(this.TW,this),5E3));var c=[];this.jb.listId==b.listId&&this.jb.videoId==b.videoId&&this.jb.index==b.index||c.push("remoteQueueChange");this.jb.o==b.o&&this.jb.volume==b.volume&&this.jb.muted==b.muted&&W7(this.jb)==W7(b)&&g.Jg(this.jb.A)==g.Jg(b.A)||c.push("remotePlayerChange");this.jb.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.pa;g8.prototype.aa=function(){var a=this.o.F.id,b=g.Ka(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.aa;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ba=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ba;g8.prototype.ga=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.ga;g8.prototype.xa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.ou(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.xa;g8.prototype.ma=function(a,b){m8(this,a,b);REa(this)};
g8.prototype.sendMessage=g8.prototype.ma;g.C(n8,n7);g.h=n8.prototype;g.h.Be=function(a){return this.kd.$_gs(a)};
g.h.contains=function(a){return!!this.kd.$_c(a)};
g.h.get=function(a){return this.kd.$_g(a)};
g.h.start=function(){this.kd.$_st()};
g.h.add=function(a,b,c){this.kd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.kd.$_r(a,b,c)};
g.h.Dr=function(a,b,c,d){this.kd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.A.length;a<b;++a)this.kd.$_ubk(this.A[a]);this.A.length=0;this.kd=null;n8.fa.Y.call(this)};
g.h.nY=function(){this.V("screenChange")};
g.h.oU=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.oY;w7.prototype.$_gsppc=w7.prototype.aH;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Dr;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Be;w7.prototype.$_gos=w7.prototype.ZG;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.ae;var o8=null,p8=null,E8=null,t8=[];g.r(F8,g.M);g.h=F8.prototype;
g.h.Y=function(){g.M.prototype.Y.call(this);this.B.stop();this.C.stop();this.K.stop();this.M();this.o.unsubscribe("proxyStateChange",this.AE,this);this.o.unsubscribe("remotePlayerChange",this.An,this);this.o.unsubscribe("remoteQueueChange",this.Dq,this);this.o.unsubscribe("autoplayUpNext",this.WD,this);this.o.unsubscribe("previousNextChange",this.xE,this);this.o.unsubscribe("nowAutoplaying",this.oE,this);this.o.unsubscribe("autoplayDismissed",this.VD,this);this.o=this.G=null};
g.h.TC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).rb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Bm(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Kx(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Kx(this.T.getVideoData(1).videoId,c)}};
g.h.lS=function(a){this.K.sL(a)};
g.h.OX=function(a){this.TC("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.lG=function(){var a=this.T.Ec("captions","track");g.Zb(a)||J8(this,a)};
g.h.lE=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.An,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.An,this)}};
g.h.GT=function(){g.Zb(this.D)||lFa(this,this.D);this.F=!1};
g.h.AE=function(a,b){this.C.stop();2==b&&this.iG()};
g.h.An=function(){if(I8(this)){this.B.stop();var a=a8(this.o);switch(a.o){case 1081:case 1:H8(this,new g.VP(8));this.hG();break;case 1085:case 3:H8(this,new g.VP(9));break;case 1083:case 0:H8(this,new g.VP(2));this.J.stop();G8(this,this.T.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.VP(4));break;case 2:H8(this,new g.VP(4));G8(this,W7(a));break;case -1:H8(this,new g.VP(64));break;case -1E3:H8(this,new g.VP(128,{errorCode:"mdx.remoteerror",message:"Video ini tidak tersedia untuk pemutaran jarak jauh"}))}a=
a8(this.o).A;var b=this.D;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.D=a,lFa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.HG()}else kFa(this)};
g.h.xE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Dq=function(){I8(this)||kFa(this)};
g.h.xK=function(){this.o.Xz()};
g.h.WD=function(a){a&&(a=g.AE("/watch_queue_ajax",{method:"GET",bd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.TV,this)}))&&(this.M=(0,g.B)(a.abort,a))};
g.h.TV=function(a,b){var c=new g.IO(g.Y(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.oE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.VD=function(){this.T.V("mdxautoplaycanceled")};
g.h.rQ=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.XG(a)};
g.h.HG=function(){if(I8(this)){var a=a8(this.o);this.A.Ga(this.O);a.muted?this.T.mute():this.T.ug();this.T.setVolume(a.volume);this.O=this.A.R(this.T,"onVolumeChange",this.lE)}};
g.h.hG=function(){this.B.stop();if(!this.o.la()){var a=a8(this.o);a.rb()&&H8(this,new g.VP(8));G8(this,W7(a));this.B.start()}};
g.h.iG=function(){this.C.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.C.start()};g.r(L8,g.W);L8.prototype.D=function(a){nFa(this,a.state)};g.r(M8,g.DY);M8.prototype.K=function(){var a=this.T.Ec("remote","receivers");a&&1<a.length&&!this.T.Ec("remote","quickCast")?(this.H=g.jb(a,this.D,this),g.EY(this,(0,g.I)(a,this.D)),a=this.T.Ec("remote","currentReceiver"),this.Hf(this.D(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.D=function(a){return a.key};
M8.prototype.Gf=function(a){return"cast-selector-receiver"==a?"Transmisi...":this.H[a].name};
M8.prototype.Dd=function(a){g.DY.prototype.Dd.call(this,a);this.T.Ud("remote","currentReceiver",this.H[a]);this.C.Ob()};g.r(N8,g.HU);g.h=N8.prototype;g.h.create=function(){eFa(g.LM(g.Y(this.o)));this.F.push(g.gG("yt-remote-before-disconnect",this.hS,this));this.F.push(g.gG("yt-remote-connection-change",this.YU,this));this.F.push(g.gG("yt-remote-receiver-availability-change",this.yE,this));this.F.push(g.gG("yt-remote-auto-connect",this.WU,this));this.F.push(g.gG("yt-remote-receiver-resumed",this.VU,this));this.yE()};
g.h.load=function(){this.o.Dv();g.HU.prototype.load.call(this);this.D=new F8(this,this.o,this.A);var a=(a=jFa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));mFa(this,this.G,this.G);g.N_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.mf(this.D,this.A);this.A=this.D=null;g.HU.prototype.unload.call(this);g.N_(this.o.app,5)};
g.h.Y=function(){g.hG(this.F);g.HU.prototype.Y.call(this)};
g.h.ln=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.TC.apply(this.D,[a].concat(g.oa(c)))};
g.h.nL=function(){return this.loaded?this.D.suggestion:null};
g.h.lg=function(){return this.A?a8(this.A).lg:!1};
g.h.hasNext=function(){return this.A?a8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.fQ=function(){var a=a8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.md(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.gQ=function(){this.A&&this.A.VG()};
g.h.hQ=function(){this.A&&this.A.WG()};
g.h.hS=function(a){1==a&&(this.K=this.A?a8(this.A):null)};
g.h.YU=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.lf(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.xC(a.videoId,W7(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.yE=function(){this.H=[this.B].concat(gFa());var a=z8()||this.B;O8(this,a);this.o.ya("onMdxReceiversChange")};
g.h.WU=function(){var a=z8();O8(this,a)};
g.h.VU=function(){this.C=z8()};
g.h.eQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.iQ=function(){e8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Mc=function(){return!1};g.DX.remote=N8;})(_yt_player);
